import sys
import os

# Add backend to path so we can import from backend modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from backend.db.postgres import SessionLocal
from backend.models.complaint import Complaint

def revert_data():
    db = SessionLocal()
    try:
        # Find all complaints generated by our seeder script
        complaints_to_delete = db.query(Complaint).filter(Complaint.severity_reason == "Generated by dummy seeder").all()
        count = len(complaints_to_delete)
        
        for complaint in complaints_to_delete:
            db.delete(complaint)
            
        db.commit()
        print(f"Successfully deleted {count} dummy complaints.")
    except Exception as e:
        print(f"Error reverting data: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    revert_data()
