import sys
import os
import random
from datetime import datetime, timedelta, timezone

# Add backend to path so we can import from backend modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from backend.db.postgres import SessionLocal
from backend.models.complaint import Complaint
import uuid

OFFICERS = [
    ("Phishing/Fraud", "Insp. Rahul Sharma"),
    ("UPI/OTP Scam", "Insp. Priya Mehta"),
    ("Ransomware/Hacking", "Insp. Vikram Singh"),
    ("Identity Theft", "Insp. Rajesh Kumar"),
    ("Cyberbullying", "Insp. Amit Verma"),
    ("Financial Fraud", "Insp. Sunita Patel"),
    ("Child Exploitation", "Insp. Neha Kapoor"),
    ("Dark Web Activity", "Insp. Suresh Gupta"),
    ("Data Breach", "Insp. Anjali Rao"),
    ("Cryptocurrency Fraud", "Insp. Meera Nair")
]

STATUSES = ["pending", "processing", "resolved"]
SEVERITIES = ["Low", "Medium", "High", "Critical"]

def seed_data():
    db = SessionLocal()
    try:
        now = datetime.now(timezone.utc)
        
        # Generate 150 random complaints spread across the last 12 weeks
        for i in range(150):
            # Pick a random crime type (which implicitly maps to an officer)
            crime_type, officer = random.choice(OFFICERS)
            
            # Pick a random date within the last 12 weeks
            days_ago = random.randint(0, 12 * 7)
            random_date = now - timedelta(days=days_ago)
            
            # Pick random status and severity
            status = random.choice(STATUSES)
            severity = random.choice(SEVERITIES)
            
            c_id = str(uuid.uuid4())
            
            complaint = Complaint(
                complaint_id=c_id,
                citizen_name=f"Dummy Citizen {i}",
                phone=f"999{random.randint(1000000, 9999999)}",
                complaint_text=f"This is a dummy complaint for {crime_type}.",
                raw_text=f"This is a dummy complaint for {crime_type}.",
                crime_type=crime_type,
                severity=severity,
                severity_reason="Generated by dummy seeder",
                status=status,
                created_at=random_date,
                updated_at=random_date
            )
            db.add(complaint)
            
        db.commit()
        print("Successfully seeded 150 dummy complaints for the officer report.")
    except Exception as e:
        print(f"Error seeding data: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()
