"""Add osint_data to entities

Revision ID: db55e51e91f2
Revises: 0c57b2ffd173
Create Date: 2026-08-18 23:52:14.596385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db55e51e91f2'
down_revision: Union[str, None] = '0c57b2ffd173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('osint_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'osint_data')
    # ### end Alembic commands ###
